services:
  molly:
    build:
      context: .
    volumes:
      - .:/usr/local/bin

  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: molly
    volumes:
      - ../pgdata:/var/lib/postgresql/data

  adminer:
    image: adminer
    restart: always
    ports:
      - 80:8080
      - 443:8080
